version: '3.9'
services:
  app:
    build: .
    container_name: chatgpt_line_bot
    volumes:
      - ./src/laravel:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: chatgpt_line_bot_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chatgpt_line_bot_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
volumes:
  db_data:

